{% set name = "psycopg2-yugabytedb" %}
{% set version = "2.9.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af41d31a910435377483b0034eba6e0da1f2f8b2b5171e78e9439f8fdd66fdbc

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libpq
  run:
    - python
  run_constrained:
    - psycopg2 <0a0

test:
  imports:
  # https://github.com/yugabyte/yugabyte-db/issues/12283
  # For now, psycopg2-yugabytedb has the same underlying library (psycopg2) as the upstream driver which when installed together override one another based on the sequence of installation.
    - psycopg2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yugabyte/psycopg2
  summary: Yugabyte Psycopg2 driver is a distributed python driver for YugabyteDB built on the PostgreSQL psycopg2 driver.
  license: MPL-2.0-no-copyleft-exception
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
