{% set name = "psycopg2-yugabytedb" %}
{% set version = "2.9.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psycopg2-yugabytedb-{{ version }}.tar.gz
  sha256: 86fa49c0f74f1883174d18735b0bf6456968c836ccb4ac34d93f061e7fd4da7d

build:
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libpq
  run:
    - python
  run_constrained:
    - psycopg2 <0a0

test:
  imports:
  # https://github.com/yugabyte/yugabyte-db/issues/12283
  # For now, psycopg2-yugabytedb has the same underlying library (psycopg2) as the upstream driver which when installed together override one another based on the sequence of installation.
    - psycopg2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yugabyte/psycopg2
  summary: Yugabyte Psycopg2 driver is a distributed python driver for YugabyteDB built on the PostgreSQL psycopg2 driver.
  license: MPL-2.0-no-copyleft-exception
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
